# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
GMAIL_USERNAME: mohsin@closedeals.co
GMAIL_PASSWORD: mohsinali83
DOMAIN_NAME: example.com
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
PARSE_APP_ID: kDmDHoGKf4YGo8aCwJWqkOJbmOWtE3R2VUbeI7v0
PARSE_API_KEY: eqfkwzIh575lJWiTanlIEShH563QdiSV7cm5a6ZA

## yapjobs Bucket
AWS_KEY: AKIAJDQMQSJLG2IVF6TQ
AWS_SECRET: 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
AWS_DIRECTORY: yapjobs-dev

## Foodingo Bucket
# AWS_KEY: AKIAJQFNAMK7T5VTNIUA
# AWS_SECRET: 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
# AWS_DIRECTORY: foodingo-dishmedia
